services:
  inlislite:
    image: inlislite_v3-inlislite:latest
    container_name: inlislite_app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      # Mount the local app folder for live editing in VSCode
      - ./src:/app/web
      # Optional: persist uploads or logs
      # - ./uploads:/app/web/uploaded_files
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: inlislite_v3
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mariadb:10.3
    container_name: inlislite_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inlislite_v3
      MYSQL_USER: inlis
      MYSQL_PASSWORD: inlis
    ports:
      - "9999:3306"
    volumes:
      - ./db/inlislite_v3_dump.sql:/docker-entrypoint-initdb.d/inlislite_v3_dump.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: inlislite_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"  # Access phpMyAdmin at http://localhost:8888
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    # Optional: set language or theme
    # environment:
    #   - PMA_ARBITRARY=1
    #   - PMA_ABSOLUTE_URI=http://localhost:8888/

volumes:
  db_data:
